behaviors:
  Walker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
<<<<<<< HEAD
      learning_rate: 5.0e-4
      beta: 5.0e-3
      epsilon: 0.15
=======
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.1
>>>>>>> b7ec99307f0267ea38e6e570591cc0c3d1bf4b6d
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
<<<<<<< HEAD
    max_steps: 10.0e7
=======
    max_steps: 10.0e6
>>>>>>> b7ec99307f0267ea38e6e570591cc0c3d1bf4b6d
    time_horizon: 1000
    summary_freq: 5000
  Fighter:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 10.0e5
    time_horizon: 1000
    summary_freq: 5000
